name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests - Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          # - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
          # - ruby-head
          - jruby-9.3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rspec 
      run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Lint Ruby code with RuboCop
      run: bundle exec rubocop
